package com.gnome.gnome.models;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Represents a Weapon entity in the game, mirroring the structure of the "Weapon" table in the database.
 * The id is auto-generated by the database and updated after insertion.
 */
@Data
@AllArgsConstructor
public class Weapon {
    private int id;
    private float atkValue;
    private float cost;
    private String nameEng;
    private String nameSk;
    private String detailsEng;
    private String detailsSk;
    private String img;
}