package com.gnome.gnome.models;

import com.gnome.gnome.MainApplication;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Represents a Weapon entity in the game, mirroring the structure of the "Weapon" table in the database.
 * The id is auto-generated by the database and updated after insertion.
 */
@Data
@AllArgsConstructor
public class Weapon {
    private int id;
    private float atkValue;
    private float cost;
    private String nameEng;
    private String nameSk;
    private String detailsEng;
    private String detailsSk;
    private String img;

    public String getDetails() {
        if (MainApplication.getLang() == 'E')
            return detailsEng;
        else
            return detailsSk;
    }
    public String getName() {
        if (MainApplication.getLang() == 'E')
            return nameEng;
        else
            return nameSk;
    }
}